### PR TITLE
bump kotlinter to 3.14 and ktlint action to 1.5.1

### PR DESCRIPTION
**Pull request by christophsturm**
this replaces #83 

the reformatting is done in a separate commit to make review easier, and enable us to revert it if we want to change code style options

### CODE REVIEW

**Comment by christophsturm** [comment]
the lint task now works, but there seems to be a different problem now. I tried updating gradle to 8.0.2, but that triggered a different problem. maybe the best thing is to bump all dependencies and then revisit this pr.

**Comment by TWiStErRob** [comment]
I can help with Gradle issues if you share the problem ;) But agree, bump deps first is probably better than solving and bundling more into one PR. Tip: you can remove the kotlinter integration from this PR and just merge the ktlint action, configuration and reformat as one unit.

**Comment by christophsturm** [comment]
> This moves things forward, and future kotlinter PR will be tiny.
done!

**Comment by christophsturm** [comment]
> I can help with Gradle issues if you share the problem ;) 
you could do a separate pr that bumps gradle to 8.0.2

**Comment by christophsturm** [comment]
> Now that #87 has been merged, will we be able to leave the kotlinter plugin enabled?

no, because it still fails. the fix seems to be in kotlin 1.8, and that needs api changes. So i would keep kotlinter disabled while we still support kotlin 1.7.
I made a new kotlin 1.8.2 pr to check that it will work with 1.8.2 here: #89

**Comment by bnorm** [comment]
Thanks for this! I'm going to try and release a new version today so we can also get #89 merged and released as soon as possible.

**Pull request merged**
